let sessionId, currentQuestion, clock;
const $ = id => document.getElementById(id);
async function api(path, options = {}) { const r = await fetch('/api' + path, {headers: {'Content-Type': 'application/json'}, ...options}); if (!r.ok) throw new Error(await r.text()); return r.json(); }
function values() { return {candidate_name: $('name').value, role: $('role').value, job_description: $('jd').value, resume: $('resume').value, preparation_goal: $('goal').value, difficulty: 'medium'}; }
async function startSession() { try { const d = await api('/sessions', {method: 'POST', body: JSON.stringify(values())}); sessionId = d.session_id; currentQuestion = d.question; $('question').textContent = currentQuestion; $('setup').hidden = true; $('interview').hidden = false; $('status').textContent = `Question ${d.question_number} of ${d.total_questions}`; speakQuestion(); monitorIntegrity(); } catch (e) { $('status').textContent = e.message; } }
function speakQuestion() { speechSynthesis.speak(new SpeechSynthesisUtterance(currentQuestion)); }
async function enableCamera() { try { $('preview').srcObject = await navigator.mediaDevices.getUserMedia({video: true, audio: true}); $('status').textContent = 'Camera and microphone enabled.'; } catch (e) { $('status').textContent = 'Permission was not granted: ' + e.message; } }
async function sendAnswer() { try { const d = await api(`/sessions/${sessionId}/answer`, {method: 'POST', body: JSON.stringify({answer: $('answer').value})}); $('feedback').textContent = JSON.stringify(d.feedback, null, 2); $('answer').value = ''; if (d.complete) { $('interview').hidden = true; showReport(); } else { currentQuestion = d.next_question; $('question').textContent = currentQuestion; speakQuestion(); } } catch (e) { $('feedback').textContent = e.message; } }
function startDictation() { const R = window.SpeechRecognition || window.webkitSpeechRecognition; if (!R) return alert('Speech recognition is unavailable in this browser; type your answer instead.'); const r = new R(); r.lang = 'en-US'; r.onresult = e => $('answer').value += e.results[0][0].transcript; r.start(); }
async function startDSA() { const d = await api(`/sessions/${sessionId}/dsa/start`, {method: 'POST', body: JSON.stringify({difficulty: 'medium', duration_minutes: 20})}); $('dsaTitle').textContent = d.title; $('dsaPrompt').textContent = d.prompt; $('dsa').hidden = false; let left = d.ends_in_seconds; clock = setInterval(() => { $('timer').textContent = `Time remaining: ${Math.floor(left / 60)}:${String(left % 60).padStart(2, '0')}`; if (--left < 0) { clearInterval(clock); submitDSA(); } }, 1000); }
async function submitDSA() { clearInterval(clock); await api(`/sessions/${sessionId}/dsa/submit`, {method: 'POST', body: JSON.stringify({code: $('code').value || '# No submission', language: 'python'})}); $('dsa').hidden = true; showReport(); }
async function showReport() { const d = await api(`/sessions/${sessionId}/report`); $('reportContent').textContent = JSON.stringify(d, null, 2); $('report').hidden = false; }
function event(type, details) { if (sessionId) api(`/sessions/${sessionId}/proctor-events`, {method: 'POST', body: JSON.stringify({event_type: type, details})}); }
function monitorIntegrity() { document.addEventListener('visibilitychange', () => { if (document.hidden) event('tab_hidden', 'Interview tab was hidden'); }); document.addEventListener('fullscreenchange', () => { if (!document.fullscreenElement) event('fullscreen_exit', 'Full-screen mode exited'); }); }
