import { FaceLandmarker, FilesetResolver } from 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/+esm';

const video = document.querySelector('#camera'); const state = document.querySelector('#state'); const warning = document.querySelector('#warn');
const sessionId = new URLSearchParams(location.search).get('session_id');
const API = `/api/sessions/${sessionId}`; let warnings = 0; const cooldown = new Map(); let face, coco; let awaySince = null; let lastLip = null; let mouthSince = null; let lastVisionSent = 0; let lastObjectCheck = 0;
const now = () => performance.now();
async function event(type, details) { if (!sessionId || (cooldown.get(type) || 0) > Date.now() - 8000) return; cooldown.set(type, Date.now()); const r = await fetch(`${API}/proctor-events`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_type:type,details})}); if (r.ok) { const d=await r.json(); warnings=d.warnings; warning.textContent=`Warnings: ${warnings} / ${d.warning_limit}`; if(d.disqualified){state.textContent='Assessment locked: warning limit reached.'; video.srcObject?.getTracks().forEach(t=>t.stop());}}}
async function vision(data) { if (!sessionId || Date.now()-lastVisionSent<2000) return; lastVisionSent=Date.now(); const r=await fetch(`${API}/vision-observations`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,source:'mediapipe_tfjs_browser'})}); if(r.ok){const d=await r.json();warnings=d.warnings;warning.textContent=`Warnings: ${warnings} / ${d.warning_limit}`;}}
function brightness(){const c=document.createElement('canvas');c.width=32;c.height=24;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(video,0,0,c.width,c.height);const p=x.getImageData(0,0,c.width,c.height).data;let sum=0;for(let i=0;i<p.length;i+=4)sum+=.2126*p[i]+.7152*p[i+1]+.0722*p[i+2];return sum/(p.length/4)}
async function tick(){if(!face||video.readyState<2)return requestAnimationFrame(tick);const result=face.detectForVideo(video,now());const count=result.faceLandmarks?.length||0;let gaze=0,mouth=0;if(count){const lm=result.faceLandmarks[0];const left=lm[234],right=lm[454],nose=lm[1],top=lm[13],bottom=lm[14];const ratio=(nose.x-left.x)/(right.x-left.x); const away=Math.abs(ratio-.5)>.16;if(away){awaySince??=Date.now();gaze=(Date.now()-awaySince)/1000}else awaySince=null;const lip=Math.abs(bottom.y-top.y);if(lastLip!==null&&Math.abs(lip-lastLip)>.009){mouthSince??=Date.now();mouth=(Date.now()-mouthSince)/1000}else mouthSince=null;lastLip=lip;}const light=brightness();await vision({face_visible:count>0,people_count:count,lighting:light<55?'too_dark':light>235?'too_bright':'good',gaze_away_seconds:gaze,mouth_motion_seconds:mouth});if(coco&&Date.now()-lastObjectCheck>2500){lastObjectCheck=Date.now();const objects=await coco.detect(video);if(objects.some(o=>o.class==='cell phone'&&o.score>.55))event('suspicious_phone','Cell phone detected by client-side object detector.');if(objects.filter(o=>o.class==='person'&&o.score>.6).length>1)event('multiple_people','More than one person detected by client-side object detector.');}requestAnimationFrame(tick)}
document.addEventListener('visibilitychange',()=>{if(document.hidden)event('tab_hidden','Assessment tab became hidden.')});document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)event('fullscreen_exit','Full-screen mode exited.')});
async function start(){if(!sessionId){state.textContent='Missing session_id in URL.';return}try{video.srcObject=await navigator.mediaDevices.getUserMedia({video:{width:1280,height:720},audio:true});try{await document.documentElement.requestFullscreen()}catch{state.textContent='Camera active. Full-screen permission was declined; exiting full-screen will be logged.'}const files=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm');face=await FaceLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/latest/face_landmarker.task'},runningMode:'VIDEO',numFaces:2,outputFaceBlendshapes:true});const tf=await import('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.22.0/+esm');await tf.ready();const m=await import('https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd@2.2.3/+esm');coco=await m.load();state.textContent='Monitoring active: MediaPipe face landmarks + TensorFlow.js object detection.';document.querySelector('#enable').disabled=true;tick()}catch(e){state.textContent='Camera/model startup failed: '+e.message;event('camera_unavailable','Camera or vision model could not start.')}}document.querySelector('#enable').addEventListener('click',start);
